apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-sqs-deployment
  annotations:
    iam.amazonaws.com/role: kube_template_role
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: python-sqs
      labels:
        app: python-sqs
    spec:
      containers:
      - name: python-sqs
        image: 077077460384.dkr.ecr.ap-southeast-2.amazonaws.com/python-sqs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: S3_BUCKET_NAME
            value: "isentia-testing-sqs-bucket"
          - name: SQS_QUEUE_NAME
            value: "testqueue"
          - name: SQS_REGION
            value: "ap-southeast-2"
          - name: SQS_SECURE
            value: "False"
          - name: SQS_PORT
            value: "9324"
          - name: STORM_URL
            value: "https://gnip-stream.twitter.com/stream/powertrack/accounts/BuzzNumbers/publishers/twitter/dev.json"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: awsaccount
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: aws-account
          - name: awsregion
            valueFrom:
              secretKeyRef:
                name: registry-creds
                key: awsregion
      imagePullSecrets:
        - name: registry-creds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: python-sqs-svc
  labels:
    app: python-sqs-svc
    tier: web
spec:
  type: NodePort
  selector:
    app: python-sqs
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
